### ISSUE TITLE
TypeError: not enough arguments for format string

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/maintainer-quality-tools#109]
When trying to  commit some staged changes, pre-commit git hook script fails as is shown below..

```bash
[21:28:11] ~/build/Vauxoo/project 8.0-vx#XXXX-osval✘
 # git commit -m "[REF] module: include demo" 

FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"
dirname $0

flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
status2=$?

TRAVIS_PULL_REQUEST="true" TRAVIS_BRANCH="HEAD" TRAVIS_BUILD_DIR=`pwd -P` $(dirname $0)/test_pylint
dirname $0
pwd -P
Traceback (most recent call last):
  File ".git/hooks/test_pylint", line 171, in <module>
    ] + extra_params_cmd, standalone_mode=False)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/.repo_requirements/linit_hook/travis/run_pylint.py", line 104, in main
    extra_params=extra_params)
  File "/.repo_requirements/linit_hook/travis/run_pylint.py", line 75, in run_pylint
    pylint_res = pylint.lint.Run(cmd, exit=False)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1290, in __init__
    linter.load_config_file()
  File "/usr/local/lib/python2.7/dist-packages/logilab/common/configuration.py", line 670, in load_config_file
    for option, value in parser.items(section):
  File "/usr/lib/python2.7/ConfigParser.py", line 655, in items
    for option in options]
  File "/usr/lib/python2.7/ConfigParser.py", line 666, in _interpolate
    value = value % vars
TypeError: not enough arguments for format string
pylint_status=$?
exit $((${status1} || ${status2} || ${pylint_status}))
FAIL

[21:28:33] ~/build/Vauxoo/project 8.0-vx#XXXX-osval✘
```

**Comment by osvalr** [comment]
Hi @moylop260,  have you seen this before?

**Comment by osvalr** [comment]
Maybe a typo made this to be linked with Vauxoo/runbot-addons#77

**Comment by moylop260** [comment]
I'm working here https://github.com/Vauxoo/maintainer-quality-tools/pull/110

**Comment by moylop260** [comment]
Same comment from here https://github.com/Vauxoo/maintainer-quality-tools/issues/111#issuecomment-220757951
Thanks
