### ISSUE TITLE
Path "/home/travis/maintainer-quality-tools/travis/pylint_deprecated_modules" does not exist.

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/maintainer-quality-tools#111]
```bash
extra_params_cmd ['--sys-paths', '/home/travis/maintainer-quality-tools/travis/pylint_deprecated_modules', '--extra-params', '--load-plugins=pylint_odoo', '--extra-params', '--load-plugins=pylint_odoo']
Traceback (most recent call last):
  File "/home/travis/maintainer-quality-tools/travis/test_pylint", line 99, in <module>
    ] + modules_cmd + extra_params_cmd, standalone_mode=False)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 695, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 620, in make_context
    self.parse_args(ctx, args)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 874, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1390, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1675, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1359, in full_process_value
    value = self.process_value(ctx, value)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1349, in process_value
    return self.type_cast_value(ctx, value)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1338, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1337, in _convert
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1337, in <genexpr>
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/core.py", line 1336, in _convert
    return self.type(value, self, ctx)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/types.py", line 419, in convert
    ), param, ctx)
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/click/types.py", line 68, in fail
    raise BadParameter(message, ctx=ctx, param=param)
click.exceptions.BadParameter: Path "/home/travis/maintainer-quality-tools/travis/pylint_deprecated_modules" does not exist.
+=======================================
|  Tests summary:
|---------------------------------------
| test_flake8                 Success
| test_pylint                 FAIL
+=======================================
```

**Comment by osvalr** [comment]
For an example please see travis-ci for Vauxoo/rma#123 

/cc @moylop260

**Comment by zaoral** [comment]
I present the same problem for vauxoo/yoytec#1191 and vauxoo/yoytec#1237

**Comment by moylop260** [comment]
Thanks wip...

**Comment by deivislaya** [comment]
I have also observed the same problem in PR Vauxoo/yoytec#1139[](https://github.com/Vauxoo/yoytec/pull/1139)

**Comment by moylop260** [comment]
@osvalr Thanks for report this issue.
Fixed https://github.com/Vauxoo/maintainer-quality-tools/pull/113

Feel free of open this issue if you see it again.

You will need update your big image and rebuild your custom t2d image with `--no-cache` to see the result.

**Comment by osvalr** [comment]
@moylop260 thanks for your support
