### ISSUE TITLE
MailDeliveryException when executed /entrypoint.sh

### ISSUE THREAD

**Issue by erickcion** [Vauxoo/maintainer-quality-tools#119]
I am working in yoytec project and trying to execute a full test of my changes, so I did this steps:

* Checked out to my branch merge the latest of branch 8.0
* Droped all databases
* Executed `/entrypoint.sh`

In the early begining, `entrypoint.sh` script stops at:

```bash
2016-06-08 12:58:39,052 863 ERROR openerp_test openerp.addons.base.ir.ir_mail_server: Mail delivery failed via SMTP server 'localhost'.
error: 111
Connection refused
2016-06-08 12:58:39,052 863 ERROR openerp_test openerp.addons.mail.mail_mail: failed sending mail.mail 14
Traceback (most recent call last):
File "/root/odoo-8.0/addons/mail/mail_mail.py", line 306, in send
context=context)
File "/.repo_requirements/odoo/openerp/api.py", line 269, in wrapper
with profiling(): return old_api(self, *args, **kwargs)
File "/root/odoo-8.0/openerp/addons/base/ir/ir_mail_server.py", line 503, in send_email
raise MailDeliveryException(_("Mail Delivery Failed"), msg)
MailDeliveryException: ('Mail Delivery Failed', u"Mail delivery failed via SMTP server 'localhost'.\nerror: 111\nConnection refused")
```

![captura de pantalla de 2016-06-08 09 08 40](https://cloud.githubusercontent.com/assets/442938/15898741/31c52e30-2d63-11e6-856a-19ab904fd986.png)

The expected behaviour is the script to continue executing all the project tests.

A workaround I'm using right now is manually call the tests:

```bash
/root/odoo-8.0/openerp-server -d yswtest --logfile=log.log -u yoytec --test-enable --stop-after-init
```
And it's going on well by now.

**Comment by erickcion** [comment]
Maybe is a interesting point to know that before all that steps I executed an `odoo-instance restart`.

**Comment by moylop260** [comment]
It was by a change in the customer project
