### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'

### ISSUE THREAD

**Issue by osvalr** [Vauxoo/maintainer-quality-tools#220]
When running lints from hooks either manually or automatically it fails showing a python traceback.

### manually
```bash
(nodejs)(python2.7) [odoo@604f5a902249]~/build/Vauxoo/repo$
 ((af10424...))$ .git/hooks/pre-commit
Do you want to run lints? (y/N): y
```

### automatically
```bash
(nodejs)(python2.7) [odoo@604f5a902249]~/build/Vauxoo/repo$
 ((af10424...))$ git commit -m "whatever"
Do you want to run lints? (y/N): y
```

The following output contains the traceback.

```bash
FLAKE8_CONFIG_DIR="$(dirname $0)/cfg"
dirname $0

flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8__init__.cfg
status1=$?
flake8 . --config=${FLAKE8_CONFIG_DIR}/travis_run_flake8.cfg
status2=$?

TRAVIS_PULL_REQUEST="true" TRAVIS_BRANCH="HEAD" TRAVIS_BUILD_DIR=`pwd -P` $(dirname $0)/test_pylint
dirname $0
pwd -P

modules_cmd ['--path', '/home/odoo/build/Vauxoo/repo']
extra_params_cmd ['--extra-params', '--load-plugins=pylint_odoo', '--msgs-no-count', 'po-lint', '--msgs-no-count', 'bad-docstring-quotes', '--msgs-no-count', 'method-compute', '--msgs-no-count', 'method-inverse', '--msgs-no-count', 'method-search', '--msgs-no-count', 'missing-return', '--msgs-no-count', 'fixme', '--msgs-no-count', 'javascript-lint']
Traceback (most recent call last):
  File ".git/hooks/test_pylint", line 154, in <module>
    ] + modules_cmd + extra_params_cmd, standalone_mode=False)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/.repo_requirements/linit_hook/travis/run_pylint.py", line 110, in main
    extra_params=extra_params)
  File "/.repo_requirements/linit_hook/travis/run_pylint.py", line 78, in run_pylint
    pylint_res = pylint.lint.Run(cmd, exit=False)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 1218, in __init__
    ), option_groups=self.option_groups, pylintrc=self._rcfile)
  File "/usr/local/lib/python2.7/dist-packages/pylint/lint.py", line 434, in __init__
    config_file=pylintrc or config.PYLINTRC)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 448, in __init__
    self.reset_parsers(usage, version=version)
  File "/usr/local/lib/python2.7/dist-packages/pylint/config.py", line 462, in reset_parsers
    self.cfgfile_parser = configparser.ConfigParser(inline_comment_prefixes=('#', ';'))
TypeError: __init__() got an unexpected keyword argument 'inline_comment_prefixes'
pylint_status=$?
exit $((${status1} || ${status2} || ${pylint_status}))
(nodejs)(python2.7) [odoo@604f5a902249]~/build/Vauxoo/repo$
 ((af10424...))$
```

**Comment by moylop260** [comment]
Could you create a issue for pycqa/pylint project, please?
-- 
Moisés López Calderón
Vauxoo - OpenERP's Gold Partner
Mobile: (+521) 477-752-22-30
Office: (+52) 477-773-33-46
web: http://www.vauxoo.com
twitter: @vauxoo
           @moylop260
hangout: moylop260@vauxoo.com

**Comment by osvalr** [comment]
I was reading a little bit and It seems the traceback resides in `future<0.16` as mentioned in https://github.com/PyCQA/pylint/issues/1318#issuecomment-300897448. I've tested in one runbot instances and it worked installing `future==0.16`.

**Comment by osvalr** [comment]
I've proposed https://github.com/Vauxoo/maintainer-quality-tools/pull/221 in order to install `future==0.16`
