### ISSUE TITLE
Error when using variable $EXCLUDE_LINT with several modules

### ISSUE THREAD

**Issue by luisg123v** [Vauxoo/maintainer-quality-tools#268]
I'm trying to set the environment variable `$EXCLUDE_LINT` with several modules, separated by commas, to prevent them from being lint-tested:
```
EXCLUDE_LINT: "module1,module2,module3"
```

However, when I do so, I get the following exceptions:

```
Traceback (most recent call last):
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/types.py", line 412, in convert
    st = os.stat(rv)
FileNotFoundError: [Errno 2] No such file or directory: '/builds/vauxoo-dev/inteco/ir_attachment_force_storage,ir_attachment_s3,ir_attachment_url'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/maintainer-quality-tools/travis/test_pylint", line 184, in <module>
    ] + modules_changed_cmd + extra_params_cmd, standalone_mode=False)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 696, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 621, in make_context
    self.parse_args(ctx, args)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 880, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1396, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1681, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1365, in full_process_value
    value = self.process_value(ctx, value)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1355, in process_value
    return self.type_cast_value(ctx, value)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1344, in type_cast_value
    return _convert(value, (self.nargs != 1) + bool(self.multiple))
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1343, in _convert
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1343, in <genexpr>
    return tuple(_convert(x, level - 1) for x in value or ())
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/core.py", line 1342, in _convert
    return self.type(value, self, ctx)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/types.py", line 38, in __call__
    return self.convert(value, param, ctx)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/types.py", line 419, in convert
    ), param, ctx)
  File "/.repo_requirements/virtualenv/python3.5/lib/python3.5/site-packages/click/types.py", line 68, in fail
    raise BadParameter(message, ctx=ctx, param=param)
click.exceptions.BadParameter: Path "ir_attachment_force_storage,ir_attachment_s3,ir_attachment_url" does not exist.
```

[Here](https://git.vauxoo.com/vauxoo-dev/inteco/-/jobs/68827) is the full log and [here](https://git.vauxoo.com/vauxoo/inteco/merge_requests/319) the MR

**Comment by luisg123v** [comment]
FYI @moylop260

**Comment by luisg123v** [comment]
I noticed this also happens when using `$INCLUDE_LINT`, see [this log](https://git.vauxoo.com/vauxoo-dev/inteco/-/jobs/68907)

**Comment by tomeyro** [comment]
:+1:

This also happens in vauxoo/qualifirst module at gitlab.
